package com.mediasage.data.local.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.TypeConverters
import com.mediasage.data.local.dao.DailyReflectionDao
import com.mediasage.data.local.dao.DayAssignmentDao
import com.mediasage.data.local.dao.DiscoveredQuoteDao
import com.mediasage.data.local.dao.EncouragementDao
import com.mediasage.data.local.dao.FigureDao
import com.mediasage.data.local.dao.HeadlineDao
import com.mediasage.data.local.dao.LocalAccountKeyDao
import com.mediasage.data.local.dao.ParkedDailyReflectionDao
import com.mediasage.data.local.dao.QuoteDao
import com.mediasage.data.local.dao.SyncMetaDao
import com.mediasage.data.local.dao.UserReflectionNoteDao
import com.mediasage.data.local.entity.DailyReflectionEntity
import com.mediasage.data.local.entity.DayAssignmentEntity
import com.mediasage.data.local.entity.DiscoveredQuoteEntity
import com.mediasage.data.local.entity.EncouragementEntity
import com.mediasage.data.local.entity.FigureEntity
import com.mediasage.data.local.entity.HeadlineEntity
import com.mediasage.data.local.entity.LocalAccountKeyEntity
import com.mediasage.data.local.entity.ParkedDailyReflectionEntity
import com.mediasage.data.local.entity.QuoteEntity
import com.mediasage.data.local.entity.ReadHeadlineEntity
import com.mediasage.data.local.entity.SyncMetaEntity
import com.mediasage.data.local.entity.UserReflectionNoteEntity

@Database(
    entities = [
        FigureEntity::class,
        QuoteEntity::class,
        HeadlineEntity::class,
        EncouragementEntity::class,
        SyncMetaEntity::class,
        DailyReflectionEntity::class,
        DayAssignmentEntity::class,
        DiscoveredQuoteEntity::class,
        UserReflectionNoteEntity::class,
        ReadHeadlineEntity::class,
        LocalAccountKeyEntity::class,
        ParkedDailyReflectionEntity::class,
    ],
    version = 40,
    exportSchema = true
)
@TypeConverters(Converters::class)
@ConstructedBy(MediaSageDatabaseConstructor::class)
abstract class MediaSageDatabase : RoomDatabase() {
    abstract fun figureDao(): FigureDao
    abstract fun quoteDao(): QuoteDao
    abstract fun headlineDao(): HeadlineDao
    abstract fun encouragementDao(): EncouragementDao
    abstract fun syncMetaDao(): SyncMetaDao
    abstract fun dailyReflectionDao(): DailyReflectionDao
    abstract fun dayAssignmentDao(): DayAssignmentDao
    abstract fun discoveredQuoteDao(): DiscoveredQuoteDao
    abstract fun userReflectionNoteDao(): UserReflectionNoteDao
    abstract fun localAccountKeyDao(): LocalAccountKeyDao
    abstract fun parkedDailyReflectionDao(): ParkedDailyReflectionDao
}

// KMP Room requires this — the implementation is generated by KSP at compile time
@Suppress("NO_ACTUAL_FOR_EXPECT", "EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
expect object MediaSageDatabaseConstructor : RoomDatabaseConstructor<MediaSageDatabase> {
    override fun initialize(): MediaSageDatabase
}
