-- One-time cleanup of verified quote source strings so each points to a work in seed_works.sql
-- (or to the biography it was recorded in, as "Cited in ..."), and un-verify quotes no credible source supports. No schema change.
-- seed_quotes.sql already carries these values; run this once in the Supabase SQL Editor.
BEGIN;
-- short-title duplicate removed
UPDATE quotes SET source = 'A Treatise Concerning Religious Affections (1746)' WHERE figure_id = 8 AND source = 'Religious Affections (1746)';
-- standard title
UPDATE quotes SET source = 'On Correcting the Studies of Youth, inaugural address at Wittenberg (1518)' WHERE figure_id = 12 AND source = 'Address to Youth at Wittenberg (1518)';
-- short-title duplicate removed
UPDATE quotes SET source = 'Spiritual Depression: Its Causes and Cures (1965)' WHERE figure_id = 22 AND source = 'Spiritual Depression (1965)';
-- same work as the Earlier Rule
UPDATE quotes SET source = 'The Earlier Rule (Regula non bullata), Chapter 17 (1221)' WHERE figure_id = 32 AND source = 'The Rule of 1221, Chapter 17';
-- preface is part of the Commentary
UPDATE quotes SET source = 'Commentary on Ezekiel, Preface (circa 415 AD)' WHERE figure_id = 49 AND source = 'Preface to Ezekiel (circa 415 AD)';
-- drop trailing 'speech'
UPDATE quotes SET source = 'I Have a Dream (August 28, 1963)' WHERE figure_id = 51 AND source = 'I Have a Dream speech (August 28, 1963)';
-- drop trailing 'speech'
UPDATE quotes SET source = 'I''ve Been to the Mountaintop (April 3, 1968)' WHERE figure_id = 51 AND source = 'I''ve Been to the Mountaintop speech (April 3, 1968)';
-- standard title; drop 'speech'
UPDATE quotes SET source = 'Ain''t I a Woman? Women''s Rights Convention, Akron, Ohio (1851)' WHERE figure_id = 54 AND source = 'Ain''t I a Woman? speech at the Women''s Rights Convention, Akron, Ohio (1851)';
-- 'shoulders of giants' is from his letter to Hooke, not the Royal Society
UPDATE quotes SET source = 'Letter to Robert Hooke (February 5, 1676)' WHERE figure_id = 66 AND source = 'Letter to the Royal Society (cited in Frank Manuel, A Portrait of Isaac Newton, 1968)';
-- essay covered by collection; first appeared in 1625 edition
UPDATE quotes SET source = 'Essays, Of Truth (1625)' WHERE figure_id = 70 AND source = 'Essays: Of Truth (1601)';
-- essay covered by collection; first appeared in 1625 edition
UPDATE quotes SET source = 'Essays, Of Adversity (1625)' WHERE figure_id = 70 AND source = 'Essays: Of Adversity (1601)';
-- essay covered by collection; first appeared in 1612 edition
UPDATE quotes SET source = 'Essays, Of Atheism (1612)' WHERE figure_id = 70 AND source = 'Essays: Of Atheism (1601)';
-- unidentified letter (likely to Herwart von Hohenburg, 1598) known via Caspar
UPDATE quotes SET source = 'Cited in Max Caspar, Kepler (1959)' WHERE figure_id = 72 AND source = 'Letter (cited in Max Caspar, Kepler, 1959)';
-- full standard title
UPDATE quotes SET source = 'God''s Undertaker: Has Science Buried God? (2007)' WHERE figure_id = 80 AND source = 'God''s Undertaker (2007)';
-- book about her by Muggeridge
UPDATE quotes SET source = 'Cited in Malcolm Muggeridge, Something Beautiful for God (1971)' WHERE figure_id = 81 AND source = 'Something Beautiful for God by Malcolm Muggeridge (1971)';
-- biography by his son and daughter-in-law
UPDATE quotes SET source = 'Cited in Howard Taylor and Geraldine Taylor, Hudson Taylor''s Spiritual Secret (1932)' WHERE figure_id = 82 AND source = 'Hudson Taylor''s Spiritual Secret (1932)';
-- biography by his son and daughter-in-law
UPDATE quotes SET source = 'Cited in Howard Taylor and Geraldine Taylor, Hudson Taylor''s Spiritual Secret (1932)' WHERE figure_id = 82 AND source = 'Hudson Taylor''s Spiritual Secret by Dr. and Mrs. Howard Taylor (1932)';
-- standard title of the published journals
UPDATE quotes SET source = 'The Journals of Jim Elliot (1948)' WHERE figure_id = 85 AND source = 'Journal of Jim Elliot (1948)';
-- standard title of the published journals
UPDATE quotes SET source = 'The Journals of Jim Elliot (1949)' WHERE figure_id = 85 AND source = 'Journal of Jim Elliot (1949)';
-- standard title of the published journals
UPDATE quotes SET source = 'The Journals of Jim Elliot (1950)' WHERE figure_id = 85 AND source = 'Journal of Jim Elliot (1950)';
-- standard title of the published journals
UPDATE quotes SET source = 'The Journals of Jim Elliot (1951)' WHERE figure_id = 85 AND source = 'Journal of Jim Elliot (1951)';
-- standard title of the published journals
UPDATE quotes SET source = 'The Journals of Jim Elliot (1952)' WHERE figure_id = 85 AND source = 'Journal of Jim Elliot (1952)';
-- standard title of the published journals
UPDATE quotes SET source = 'The Journals of Jim Elliot (October 28, 1949)' WHERE figure_id = 85 AND source = 'Journal of Jim Elliot (October 28, 1949)';
-- biography by Elisabeth Elliot
UPDATE quotes SET source = 'Cited in Elisabeth Elliot, Shadow of the Almighty (1958)' WHERE figure_id = 85 AND source = 'Shadow of the Almighty by Elisabeth Elliot (1958)';
-- full standard title
UPDATE quotes SET source = 'The Unoccupied Mission Fields of Africa and Asia (1911)' WHERE figure_id = 97 AND source = 'The Unoccupied Mission Fields (1911)';
-- confirmed: CCEL, Sermons on Several Occasions, 'The Use of Money' https://www.ccel.org/ccel/wesley/sermons.v.l.html , section III.1: "Having, First, gained all you can, and, Secondly saved all you can, Then 'give all you can.'" Section II.1: "the second rule of Christian prudence is, 'Save all you can.'"
UPDATE quotes SET source = 'The Use of Money, sermon (1744)' WHERE figure_id = 5 AND source = 'Sermon: The Use of Money (1744)' AND text = 'Earn all you can, save all you can, give all you can.';
-- confirmed: Wikisource, Sermons on Several Occasions/Volume I/Preface https://en.wikisource.org/wiki/Sermons_on_Several_Occasions/Volume_I/Preface , paragraph 5: "I want to know one thing, — the way to heaven; how to land safe on that happy shore. God himself has condescended to teach the way: For this very end
UPDATE quotes SET source = 'Sermons on Several Occasions, Preface, §5 (1746)' WHERE figure_id = 5 AND source = 'Preface to Sermons on Several Occasions (1746)' AND text = 'I want to know one thing — the way to heaven. God himself has condescended to teach the way.';
-- cited: Wikiquote William Tyndale https://en.wikiquote.org/wiki/William_Tyndale : "I defie the Pope and all his lawes. If God spare my life, ere many yeares I wyl cause a boy that driveth the plough to know more of the Scripture, than he doust." Source given: Foxe, Actes and Monuments; the variant it lists,
UPDATE quotes SET source = 'Cited in John Foxe, Actes and Monuments (1563)' WHERE figure_id = 7 AND source = 'Response to Thomas More (circa 1531)' AND text = 'I defy the Pope and all his laws. If God spare my life, ere many years I will cause a boy that driveth the plough shall know more of the Scripture than thou doest.';
-- confirmed: Project Gutenberg, Knox History of the Reformation (ed. Lennox) https://www.gutenberg.org/files/48250/48250-h/48250-h.htm , the interview on the Queen's marriage, after the 1563 Parliament: "Outside the preaching place, Madam, I think few have occasion to be offended at me; and there, Madam, I am no
UPDATE quotes SET source = 'History of the Reformation in Scotland, interview with Mary Queen of Scots (1563)' WHERE figure_id = 10 AND source = 'Letter to Mary Queen of Scots (1561)' AND text = 'Madam, I am not master of myself, but must obey him who commands me to speak plain, and to flatter no flesh upon the face of the earth.';
-- cited: https://www.gutenberg.org/cache/epub/2056/pg2056.txt (Smith, ch. on Carey's last days, quoting Culross): 'Mr. Duff, you have been speaking about Dr. Carey, Dr. Carey; When I am gone, say nothing about Dr. Carey--speak about Dr. Carey's Saviour.' Footnote [33]: 'William Carey, by James Culross, D.D.,
UPDATE quotes SET source = 'Cited in George Smith, The Life of William Carey, Shoemaker and Missionary (1885)' WHERE figure_id = 18 AND source = 'Memoir of William Carey, cited in George Smith''s biography (1885)' AND text = 'When I am gone, say nothing about Dr. Carey — speak about Dr. Carey''s Saviour.';
-- cited: Wording matches Spinka's translation of Mladoňovice's Relatio; widely quoted with the identical phrase 'drawing upon the sayings and positions of the holy doctors, I am ready to die today' (e.g. https://www.christianity.com/wiki/people/the-tragic-trial-and-death-of-jan-hus-11633059.html). Older tran
UPDATE quotes SET source = 'Cited in Peter of Mladoňovice, John Hus at the Council of Constance, tr. Matthew Spinka (1965)' WHERE figure_id = 20 AND source = 'Final sermon before execution (1415)' AND text = 'God is my witness that the things charged against me I have never preached. In the same truth of the Gospel which I have written, taught, and preached, drawing upon the sayings and positions of the holy doctors, I am ready to die today.';
-- cited: Wikiquote (https://en.wikiquote.org/wiki/William_Wilberforce): 'Never, never will we desist till we have wiped away this scandal from the Christian name, released ourselves from the load of guilt...' - Speech before the House of Commons (18 April 1791). Google Books full-text search for the phrase (
UPDATE quotes SET source = 'Cited in Cobbett''s Parliamentary History of England, vol. 29 (1817)' WHERE figure_id = 52 AND source = 'Journal entry (1788)' AND text = 'Never, never will we desist till we have wiped away this scandal from the Christian name, released ourselves from the load of guilt.';
-- cited: Maui Media Q&A with Tutu about the book (https://mauimedia.com/godhasadream/q-and-a-with-desmond-tutu-about-god-has-a-dream/): 'God's dream is that you and I and all of us will realize that we are family, that we are made for togetherness, for goodness, and for compassion.' Also PDF: https://mauimed
UPDATE quotes SET source = 'Cited in publisher Q&A on God Has a Dream (2004)' WHERE figure_id = 55 AND source = 'God Has a Dream: A Vision of Hope for Our Time (2004)' AND text = 'God''s dream is that you and I and all of us will realize that we are family, that we are made for togetherness, for goodness, and for compassion.';
-- cited: Wikiquote Desmond Tutu (https://en.wikiquote.org/wiki/Desmond_Tutu) records it as quoted in Brown, Unexpected News (1984), p. 19, with continuation 'If an elephant has its foot on the tail of a mouse and you say that you are neutral, the mouse will not appreciate your neutrality.'
UPDATE quotes SET source = 'Cited in Robert McAfee Brown, Unexpected News: Reading the Bible with Third World Eyes (1984)' WHERE figure_id = 55 AND source = 'Address at the General Convention of the Episcopal Church (2006)' AND text = 'If you are neutral in situations of injustice, you have chosen the side of the oppressor.';
-- confirmed: Frederick Douglass Papers Project digital edition (https://frederickdouglasspapersproject.com/s/digitaledition/item/16068): 'The sunlight that brought life and healing to you, has brought stripes and death to me. This Fourth [of] July is yours, not mine. You may rejoice, I must mourn.'
UPDATE quotes SET source = 'What to the Slave Is the Fourth of July? (July 5, 1852)' WHERE figure_id = 56 AND source = 'Speech: What to the Slave Is the Fourth of July? (July 5, 1852)' AND text = 'This Fourth July is yours, not mine. You may rejoice, I must mourn.';
-- confirmed: Frederick Douglass Papers Project (https://frederickdouglasspapersproject.com/s/digitaledition/item/10509): 'Find out just what any people will quietly submit to ... and these will continue till they are resisted with either words or blows, or with both. The limits of tyrants are prescribed by the e
UPDATE quotes SET source = 'The Significance of Emancipation in the West Indies, address at Canandaigua, N.Y. (August 3, 1857)' WHERE figure_id = 56 AND source = 'Speech: What to the Slave Is the Fourth of July? (July 5, 1852)' AND text = 'The limits of tyrants are prescribed by the endurance of those whom they oppress.';
-- cited: Google Books search (https://www.google.com/books/feeds/volumes?q=%22Christ+for+the+world,+for+the+world+needs+Christ%22+Liddell): Wilson, Complete Surrender, describes the phrase called out as his train left Edinburgh; St. Andrew's Cross (1924) labels it 'Liddell's Motto'; Alistair Begg, Brave by F
UPDATE quotes SET source = 'Cited in Julian Wilson, Complete Surrender: A Biography of Eric Liddell (1996)' WHERE figure_id = 59 AND source = 'Letter from Weihsien internment camp (1943)' AND text = 'Christ for the world, for the world needs Christ.';
-- cited: Hodder, popular ed. 1892 (archive.org https://archive.org/download/cu31924030334779/cu31924030334779_djvu.txt), final chapter: 'in conversation with a friend, he had said: "When I feel age creeping on me and know I must soon die - I hope it is not wrong to say it - but I cannot bear to leave the wor
UPDATE quotes SET source = 'Cited in Edwin Hodder, The Life and Work of the Seventh Earl of Shaftesbury (1886)' WHERE figure_id = 60 AND source = 'Diary entry (cited in Edwin Hodder, The Life of the Earl of Shaftesbury, 1886)' AND text = 'I cannot bear to leave the world with all the misery in it.';
-- confirmed: https://archive.org/stream/drlivingstonesca00livi/drlivingstonesca00livi_djvu.txt — Lecture I ('delivered in the Senate-House, on Friday, 4th December, 1857'), end of lecture: 'I beg to direct your attention to Africa;—I know that in a few years I shall be cut off in that country, which is now open;
UPDATE quotes SET source = 'Dr. Livingstone''s Cambridge Lectures, Lecture I, Senate House (December 4, 1857)' WHERE figure_id = 84 AND source = 'Cambridge address, December 4, 1857' AND text = 'I beg to direct your attention to Africa. I know that in a few years I shall be cut off in that country, which is now open. Do not let it be shut again!';
-- cited: https://www.gutenberg.org/cache/epub/13262/pg13262.txt — Chapter III: 'he told them that he was at their disposal "to go anywhere--provided it be FORWARD."' (letter to the LMS Directors from Mabotsa, c.1843; Wikipedia identifies recipient as LMS secretary Arthur Tidman).
UPDATE quotes SET source = 'Cited in William Garden Blaikie, The Personal Life of David Livingstone (1880)' WHERE figure_id = 84 AND source = 'Journals of David Livingstone (cited in W. Garden Blaikie, The Personal Life of David Livingstone, 1880)' AND text = 'I am prepared to go anywhere, provided it be forward.';
-- cited: https://www.gutenberg.org/cache/epub/13262/pg13262.txt — Chapter XVII: at the prize examination of Oswell's school in Hamilton (1865), per reminiscence of Dr. Loudon, 'he had just two things to say to them--"FEAR GOD, AND WORK HARD." These appear to have been Livingstone's last public words in his n
UPDATE quotes SET source = 'Cited in William Garden Blaikie, The Personal Life of David Livingstone (1880)' WHERE figure_id = 84 AND source = 'Journals (cited in Blaikie, 1880)' AND text = 'Fear God and work hard.';
-- cited: https://en.wikiquote.org/wiki/William_Booth — sourced entry 'Go for souls and go for the worst.' citing Hulda Friedrichs, The Life of General Booth (1913). Could not fetch a full-text scan of Friedrichs to confirm the page directly.
UPDATE quotes SET source = 'Cited in Hulda Friedrichs, The Life of General Booth (1913)' WHERE figure_id = 86 AND source = 'The Founder Speaks Again by Cyril Barnes (1960, compiled)' AND text = 'Go for souls, and go for the worst.';
-- cited: https://en.wikiquote.org/wiki/William_Booth — sourced: 'While Women weep as they do now, I'll fight. While little children go hungry, as they do now, I'll fight...' citing Booth the Beloved (1949), pp.122-124. Full-text grep of In Darkest England (https://www.gutenberg.org/cache/epub/475/pg475.txt):
UPDATE quotes SET source = 'Cited in J. Evan Smith, Booth the Beloved (1949)' WHERE figure_id = 86 AND source = 'In Darkest England (1890)' AND text = 'While women weep as they do now, I''ll fight; while little children go hungry as they do now, I''ll fight.';
-- confirmed: https://www.gutenberg.org/cache/epub/475/pg475.txt — Part 1, Chapter 5: 'But what is the use of preaching the Gospel to men whose whole attention is concentrated upon a mad, desperate struggle to keep themselves alive? You might as well give a tract to a shipwrecked sailor...'
UPDATE quotes SET source = 'In Darkest England and the Way Out, Part 1, ch. 5 ''On the Verge of the Abyss'' (1890)' WHERE figure_id = 86 AND source = 'In Darkest England (1890)' AND text = 'What is the use of preaching the Gospel to men whose whole attention is concentrated upon a mad, desperate struggle to keep themselves alive?';
-- cited: https://gregburdine.com/inspiring-quotes-gates-splendor/ — excerpts from ch. 15 'Why Did the Men Go?' include '...the word sacrifice would disappear from our lips and thoughts; we would hate the things that seem now so dear to us; our lives would suddenly be too short...'
UPDATE quotes SET source = 'Cited in Elisabeth Elliot, Through Gates of Splendor (1957)' WHERE figure_id = 98 AND source = 'Journal of Nate Saint (cited in Elisabeth Elliot, Through Gates of Splendor, 1957)' AND text = 'If God would grant us the vision, the word sacrifice would disappear from our lips and thoughts.';
-- new verified quote: https://wesley.nnu.edu/john-wesley/the-sermons-of-john-wesley-1872-edition/sermon-1-salvation-by-faith/ — introduction, paragraph 3
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 5, 'Salvation by Faith, sermon, Introduction §3 (1738)', 'Grace is the source, faith the condition, of salvation.', 'grace,faith,salvation,assurance', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 5 AND text = 'Grace is the source, faith the condition, of salvation.');
-- new verified quote: https://pages.uoregon.edu/sshoemak/323/texts/Wesley%20Character.htm — The Character of a Methodist, paragraph 8
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 5, 'The Character of a Methodist, §8 (1742)', 'In retirement or company, in leisure, business, or conversation, his heart is ever with the Lord. Whether he lie down or rise up, God is in all his thoughts; he walks with God continually, having the loving eye of his mind still fixed upon him, and everywhere "seeing Him that is invisible."', 'prayer,devotion,presence_of_god,faithfulness', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 5 AND text = 'In retirement or company, in leisure, business, or conversation, his heart is ever with the Lord. Whether he lie down or rise up, God is in all his thoughts; he walks with God continually, having the loving eye of his mind still fixed upon him, and everywhere "seeing Him that is invisible."');
-- new verified quote: https://pages.uoregon.edu/sshoemak/323/texts/Wesley%20Character.htm — The Character of a Methodist, paragraph 9
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 5, 'The Character of a Methodist, §9 (1742)', 'And he accordingly loves his neighbour as himself; he loves every man as his own soul. His heart is full of love to all mankind, to every child of "the Father of the spirits of all flesh."', 'love,neighbor,compassion,community', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 5 AND text = 'And he accordingly loves his neighbour as himself; he loves every man as his own soul. His heart is full of love to all mankind, to every child of "the Father of the spirits of all flesh."');
-- new verified quote: https://ccel.org/ccel/w/whitefield/sermons/cache/sermons.txt — Selected Sermons of George Whitefield (CCEL), 'The Method of Grace', application section
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 9, 'The Method of Grace, sermon (1741)', 'Such as have got peace with God, if you are under trials, fear not, all things shall work for your good; if you are under temptations, fear not, if he has spoken peace to your hearts, all these things shall be for your good.', 'peace,trials,hope,providence', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 9 AND text = 'Such as have got peace with God, if you are under trials, fear not, all things shall work for your good; if you are under temptations, fear not, if he has spoken peace to your hearts, all these things shall be for your good.');
-- new verified quote: https://ccel.org/ccel/w/whitefield/sermons/cache/sermons.txt — 'The Method of Grace', application section (exhortation against conformity to the world)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 9, 'The Method of Grace, sermon (1741)', 'Christians should be singularly good, bold for their Lord, that all who are with you may take notice that you have been with Jesus.', 'boldness,witness,holiness,discipleship', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 9 AND text = 'Christians should be singularly good, bold for their Lord, that all who are with you may take notice that you have been with Jesus.');
-- new verified quote: https://ccel.org/ccel/w/whitefield/sermons/cache/sermons.txt — 'The Lord Our Righteousness', near the end of the argument section (after the reference to Stoddard)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 9, 'The Lord Our Righteousness, sermon (1741)', 'For why should I lean upon a broken reed, when I can have the rock of ages to stand upon, that never can be moved?', 'faith,assurance,trust,righteousness', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 9 AND text = 'For why should I lean upon a broken reed, when I can have the rock of ages to stand upon, that never can be moved?');
-- new verified quote: https://ccel.org/ccel/w/whitefield/sermons/cache/sermons.txt — 'The Lord Our Righteousness', application section
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 9, 'The Lord Our Righteousness, sermon (1741)', 'O think of his dying love! Let that love constrain you to obedience! Having much forgiven, love much.', 'love,gratitude,obedience,forgiveness', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 9 AND text = 'O think of his dying love! Let that love constrain you to obedience! Having much forgiven, love much.');
-- new verified quote: https://ccel.org/ccel/w/whitefield/sermons/cache/sermons.txt — 'Christ, the Believer's Wisdom, Righteousness, Sanctification and Redemption', section 4 (redemption of the body)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 9, 'Christ the Believer''s Wisdom, Righteousness, Sanctification, and Redemption, sermon', 'Fear not, therefore, O believers, to look into the grave: for to you it is not other than a consecrated dormitory, where your bodies shall sleep quietly until the morning of the resurrection;', 'hope,resurrection,death,comfort', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 9 AND text = 'Fear not, therefore, O believers, to look into the grave: for to you it is not other than a consecrated dormitory, where your bodies shall sleep quietly until the morning of the resurrection;');
-- new verified quote: https://ccel.org/ccel/w/whitefield/sermons/cache/sermons.txt — sermon titled 'On Regeneration' in CCEL (text 2 Cor 5:17, opens 'The doctrine of our regeneration, or new birth in Christ Jesus'), third inference
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 9, 'The Nature and Necessity of Our Regeneration or New Birth in Christ Jesus, sermon (1737)', 'It is not enough to turn from profaneness to civility; but thou must turn from civility to godliness.', 'regeneration,repentance,holiness,conversion', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 9 AND text = 'It is not enough to turn from profaneness to civility; but thou must turn from civility to godliness.');
-- new verified quote: https://www.gutenberg.org/cache/epub/28104/pg28104.txt — The Pulpit of the Reformation, 'A Sermon on Isaiah XXVI' by John Knox, exposition of 'Thy dead shall live'
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 10, 'Sermon on Isaiah 26 (1565)', 'This, I say, is the victory of faith, when to the midst of death, through the light of God’s word, the afflicted see life.', 'faith,hope,resurrection,perseverance', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 10 AND text = 'This, I say, is the victory of faith, when to the midst of death, through the light of God’s word, the afflicted see life.');
-- new verified quote: https://www.gutenberg.org/cache/epub/48250/pg48250.txt — Knox, History of the Reformation (Lennox ed.), appendix 'Knox's Confession', The Preface, last sentence
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 10, 'Scots Confession, Preface (1560)', 'And therefore, by the assistance of the mighty Spirit of our Lord Jesus, we firmly promise to abide to the end in the Confession of this our Faith.', 'perseverance,faithfulness,holy_spirit,courage', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 10 AND text = 'And therefore, by the assistance of the mighty Spirit of our Lord Jesus, we firmly promise to abide to the end in the Confession of this our Faith.');
-- new verified quote: https://archive.org/download/latinworkscorres02zwin/latinworkscorres02zwin_djvu.txt — The Latin Works of Huldreich Zwingli, vol. 2 (1922), 'Sermon on the Providence of God', p. 229
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 11, 'On the Providence of God, p. 229 (1530)', 'You are God''s tool. He wills to wear you out by use, not by idleness. Oh, happy man, whom He calls to His work!', 'calling,providence,perseverance,service', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 11 AND text = 'You are God''s tool. He wills to wear you out by use, not by idleness. Oh, happy man, whom He calls to His work!');
-- new verified quote: https://www.gutenberg.org/cache/epub/275/pg275.txt — Augsburg Confession, Article XX: Of Good Works
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 12, 'Augsburg Confession, Article XX (1530)', 'Now he that knows that he has a Father gracious to him through Christ, truly knows God; he knows also that God cares for him, and calls upon God; in a word, he is not without God, as the heathen.', 'faith,grace,assurance,prayer', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 12 AND text = 'Now he that knows that he has a Father gracious to him through Christ, truly knows God; he knows also that God cares for him, and calls upon God; in a word, he is not without God, as the heathen.');
-- new verified quote: https://anglicanheritage.com/homilies/h104/ — Homily 'Of the True and Lively Faith', third part, paragraph 18
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 16, 'Book of Homilies, A Short Declaration of the True, Lively, and Christian Faith, Part 3 (1547)', 'If all the world were on our side, and God against us, what could the world avail us? Therefore let us set our whole faith and trust in God, and neither the world, the devil, nor all the power of them, shall prevail against us.', 'faith,trust,courage,sovereignty', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 16 AND text = 'If all the world were on our side, and God against us, what could the world avail us? Therefore let us set our whole faith and trust in God, and neither the world, the devil, nor all the power of them, shall prevail against us.');
-- new verified quote: https://raw.githubusercontent.com/textcreationpartnership/A17086/master/A17086.xml (EEBO-TCP A17086; also https://quod.lib.umich.edu/e/eebo2/A17086.0001.001), printed p.24, section 'The meane to restore in to the Churche the right kynde of geuinge...'
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 17, 'De Regno Christi, Book 2, provision for the poor (1550)', 'For it is not ynough for the Congregations off Christ to prouyde, that men may onlie lyue, but that thei may lyue to the Lorde, for a certeyn and mutual profet betwene them selfs, and of the Churche, and commen welthe.', 'service,community,love,justice', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 17 AND text = 'For it is not ynough for the Congregations off Christ to prouyde, that men may onlie lyue, but that thei may lyue to the Lorde, for a certeyn and mutual profet betwene them selfs, and of the Churche, and commen welthe.');
-- new verified quote: https://www.gutenberg.org/cache/epub/11449/pg11449.txt, SECT. V (An Enquiry into the Duty of Christians in general)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 18, 'Enquiry into the Obligations of Christians to Use Means for the Conversion of the Heathens, Section 5 (1792)', 'Many can do nothing but pray, and prayer is perhaps the only thing in which Christians of all denominations can cordially, and unreservedly unite; but in this we may all be one, and in this the strictest unanimity ought to prevail.', 'prayer,unity,faith,community', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 18 AND text = 'Many can do nothing but pray, and prayer is perhaps the only thing in which Christians of all denominations can cordially, and unreservedly unite; but in this we may all be one, and in this the strictest unanimity ought to prevail.');
-- new verified quote: https://www.gutenberg.org/cache/epub/11449/pg11449.txt, SECT. V
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 18, 'Enquiry into the Obligations of Christians to Use Means for the Conversion of the Heathens, Section 5 (1792)', 'We must not be contented however with praying, without exerting ourselves in the use of means for the obtaining of those things we pray for.', 'prayer,diligence,faith,calling', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 18 AND text = 'We must not be contented however with praying, without exerting ourselves in the use of means for the obtaining of those things we pray for.');
-- new verified quote: https://www.gutenberg.org/cache/epub/11449/pg11449.txt, SECT. V (end of the trading-company paragraph)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 18, 'Enquiry into the Obligations of Christians to Use Means for the Conversion of the Heathens, Section 5 (1792)', 'Let then every one in his station consider himself as bound to act with all his might, and in every possible way for God.', 'calling,service,diligence,mission', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 18 AND text = 'Let then every one in his station consider himself as bound to act with all his might, and in every possible way for God.');
-- new verified quote: https://www.gutenberg.org/cache/epub/11449/pg11449.txt, SECT. V, final paragraph before FINIS
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 18, 'Enquiry into the Obligations of Christians to Use Means for the Conversion of the Heathens, Section 5 (1792)', 'Surely a crown of rejoicing like this is worth aspiring to. Surely it is worth while to lay ourselves out with all our might, in promoting the cause, and kingdom of Christ.', 'hope,mission,perseverance,calling', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 18 AND text = 'Surely a crown of rejoicing like this is worth aspiring to. Surely it is worth while to lay ourselves out with all our might, in promoting the cause, and kingdom of Christ.');
-- new verified quote: https://archive.org/download/lettersofjohnhus00husjuoft/lettersofjohnhus00husjuoft_djvu.txt, Letter LXI (p.227)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 20, 'The Letters of John Hus, Letter 61, To Henry Skopek de Duba, 9 June 1415 (1904)', 'Fear Him as the Lord Almighty, love Him as the Father most holy, ever aim at Him in mind, works, and desire. For His sake carefully abstain from sin, do all the good you can, and be not afraid of the adversities of this world.', 'courage,love,holiness,obedience', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 20 AND text = 'Fear Him as the Lord Almighty, love Him as the Father most holy, ever aim at Him in mind, works, and desire. For His sake carefully abstain from sin, do all the good you can, and be not afraid of the adversities of this world.');
-- new verified quote: https://archive.org/download/lettersofjohnhus00husjuoft/lettersofjohnhus00husjuoft_djvu.txt, Letter V (pp.29-30)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 20, 'The Letters of John Hus, Letter 5, To the People of Laun, c.1410 (1904)', 'If here we have to suffer for Christ''s sake, there we shall be blessed. It is through a cross and through afflictions that we are tried, like gold in the fire, by the Builder who formed the world out of nothing. Blessed then shall we be, if we persevere in that which is good, even to the end.', 'suffering,perseverance,hope,faith', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 20 AND text = 'If here we have to suffer for Christ''s sake, there we shall be blessed. It is through a cross and through afflictions that we are tried, like gold in the fire, by the Builder who formed the world out of nothing. Blessed then shall we be, if we persevere in that which is good, even to the end.');
-- new verified quote: https://archive.org/download/spiritualletters00fnel/spiritualletters00fnel_djvu.txt, Letter IV 'The Difficulties of a Man of the World' (p.15)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 24, 'The Spiritual Letters of Fénelon, Letters to Men, Letter 4', 'Oh, how compassionate and comforting God is to those who go to Him with hearty confidence in their troubles! Men are hard, critical, harsh, never more than half-tolerant; but God bears with all, is pitiful to all. His Goodness, His Patience and Indulgence, are boundless.', 'compassion,trust,grace,patience', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 24 AND text = 'Oh, how compassionate and comforting God is to those who go to Him with hearty confidence in their troubles! Men are hard, critical, harsh, never more than half-tolerant; but God bears with all, is pitiful to all. His Goodness, His Patience and Indulgence, are boundless.');
-- new verified quote: https://archive.org/download/a614421400wilbuoft/a614421400wilbuoft_djvu.txt, Chap. IV Sect. I (pp.121-122 of 17th ed., 1829)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 52, 'A Practical View of Christianity, Chapter 4, Section 1 (1797)', 'This is the Christian love of God! A love compounded of admiration, of preference, of hope, of trust, of joy: chastised by reverential awe, and wakeful with continual gratitude.', 'love,worship,gratitude,trust', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 52 AND text = 'This is the Christian love of God! A love compounded of admiration, of preference, of hope, of trust, of joy: chastised by reverential awe, and wakeful with continual gratitude.');
-- new verified quote: https://archive.org/download/a614421400wilbuoft/a614421400wilbuoft_djvu.txt, Chap. VII, Practical Hints to various Descriptions of Persons (p.344 of 17th ed., 1829)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 52, 'A Practical View of Christianity, Chapter 7 (1797)', 'Ever look to him for help: your only safety consists in a deep and permanent sense of your own weakness, and in a firm reliance on his strength.', 'humility,trust,faith,perseverance', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 52 AND text = 'Ever look to him for help: your only safety consists in a deep and permanent sense of your own weakness, and in a firm reliance on his strength.');
-- new verified quote: https://archive.org/download/speechesofearlof00shaf/speechesofearlof00shaf_djvu.txt, 'Legislation for the Labouring Classes' (Manchester, 26 Oct 1844), pp.150-151
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 60, 'Speeches of the Earl of Shaftesbury, Legislation for the Labouring Classes, Manchester, 26 October 1844 (1868)', 'God has given me leisure and freedom from the necessity of daily toil; and I willingly therefore devote them to the service of those people who have neither the one nor the other of these responsible gifts.', 'service,calling,justice,compassion', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 60 AND text = 'God has given me leisure and freedom from the necessity of daily toil; and I willingly therefore devote them to the service of those people who have neither the one nor the other of these responsible gifts.');
-- new verified quote: https://archive.org/download/speechesofearlof00shaf/speechesofearlof00shaf_djvu.txt, 'Young Men's Christian Association' (Manchester, 25 Mar 1856), p.305
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 60, 'Speeches of the Earl of Shaftesbury, Young Men''s Christian Association, Manchester, 25 March 1856 (1868)', 'I know no sentiment that so tends to exalt, and at the same time so tends to humble the human heart, as does the sense of direct and immediate responsibility to Almighty God.', 'responsibility,humility,faith,calling', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 60 AND text = 'I know no sentiment that so tends to exalt, and at the same time so tends to humble the human heart, as does the sense of direct and immediate responsibility to Almighty God.');
-- new verified quote: https://archive.org/download/speechesofearlof00shaf/speechesofearlof00shaf_djvu.txt, 'Sanitary Legislation' (Social Science Congress, 1858), p.308
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 60, 'Speeches of the Earl of Shaftesbury, Sanitary Legislation, Social Science Congress, 1858 (1868)', 'But when people say we should think more of the soul and less of the body, my answer is, that the same God who made the soul made the body also.', 'compassion,justice,service,creation', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 60 AND text = 'But when people say we should think more of the soul and less of the body, my answer is, that the same God who made the soul made the body also.');
-- new verified quote: https://archive.org/download/speechesofearlof00shaf/speechesofearlof00shaf_djvu.txt, 'Religious Service in Theatres' (House of Lords, 24 Feb 1860), p.335
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 60, 'Speeches of the Earl of Shaftesbury, Religious Service in Theatres, House of Lords, 24 February 1860 (1868)', 'These efforts, nevertheless, must be made; no good may be left unattempted; against hope we must believe in hope, and endeavour, though the mass be inaccessible, to rescue individuals.', 'hope,perseverance,service,compassion', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 60 AND text = 'These efforts, nevertheless, must be made; no good may be left unattempted; against hope we must believe in hope, and endeavour, though the mass be inaccessible, to rescue individuals.');
-- new verified quote: https://archive.org/download/cardiphoniaorthe00newtuoft/cardiphoniaorthe00newtuoft_djvu.txt — section 'To Mrs. G—', Letter II (series begins with Letter I dated June 20, 1776)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 62, 'Cardiphonia, Letter II to Mrs. G— (1781)', 'After all, I know the Lord keeps the key of comfort in His own hands, yet He has commanded us to attempt comforting one another.', 'comfort,encouragement,love,community', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 62 AND text = 'After all, I know the Lord keeps the key of comfort in His own hands, yet He has commanded us to attempt comforting one another.');
-- new verified quote: https://web.archive.org/web/2024/https://biologos.org/personal-stories/is-there-a-god-and-does-he-care-about-me-the-testimony-of-biologos-founder-francis-collins — paragraph beginning 'Yes, God was there with me' (article by Francis Collins, Dec 16, 2019, adapted from his BioLogos 2019 conference ta
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 75, 'Is There a God and Does He Care About Me? The Testimony of BioLogos Founder Francis Collins, BioLogos (2019)', 'I realized I’d really neglected the most important question that any of us ever asks: Is there a God, and does that God care about me?', 'faith,truth,seeking,conviction', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 75 AND text = 'I realized I’d really neglected the most important question that any of us ever asks: Is there a God, and does that God care about me?');
-- new verified quote: https://www.gutenberg.org/cache/epub/1039/pg1039.txt — Introduction (autobiographical account of his conversion)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 84, 'Missionary Travels and Researches in South Africa, Introduction (1857)', 'The perfect freeness with which the pardon of all our guilt is offered in God’s book drew forth feelings of affectionate love to Him who bought us with his blood, and a sense of deep obligation to Him for his mercy has influenced, in some small measure, my conduct ever since.', 'grace,forgiveness,gratitude,love', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 84 AND text = 'The perfect freeness with which the pardon of all our guilt is offered in God’s book drew forth feelings of affectionate love to Him who bought us with his blood, and a sense of deep obligation to Him for his mercy has influenced, in some small measure, my conduct ever since.');
-- new verified quote: https://www.gutenberg.org/cache/epub/1039/pg1039.txt — Chapter 32 (closing paragraphs)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 84, 'Missionary Travels and Researches in South Africa, Chapter 32 (1857)', 'I have not mentioned half the favors bestowed, but I may just add that no one has cause for more abundant gratitude to his fellow-men and to his Maker than I have; and may God grant that the effect on my mind be such that I may be more humbly devoted to the service of the Author of all our mercies!', 'gratitude,humility,service,devotion', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 84 AND text = 'I have not mentioned half the favors bestowed, but I may just add that no one has cause for more abundant gratitude to his fellow-men and to his Maker than I have; and may God grant that the effect on my mind be such that I may be more humbly devoted to the service of the Author of all our mercies!');
-- new verified quote: https://archive.org/download/lottiemoon0000unar/lottiemoon0000unar_djvu.txt — ch. on her country itineration from Tengchow, c. p. 109–110 (letter describing a four-day village tour, early 1880s)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 87, 'Cited in Una Roberts Lawrence, Lottie Moon (1927)', 'As you wind your way from village to village you feel it is no idle fancy that the Master walks beside you.', 'presence,mission,faith,comfort', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 87 AND text = 'As you wind your way from village to village you feel it is no idle fancy that the Master walks beside you.');
-- new verified quote: https://archive.org/download/lottiemoon0000unar/lottiemoon0000unar_djvu.txt — c. p. 144 (letter of 1887 on country work around Tengchow)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 87, 'Cited in Una Roberts Lawrence, Lottie Moon (1927)', 'I am more and more impressed by the belief that to win these people to God, we must first win them to ourselves. We need to go out and live among them, manifesting the gentle and loving spirit of our Lord.', 'love,mission,gentleness,evangelism', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 87 AND text = 'I am more and more impressed by the belief that to win these people to God, we must first win them to ourselves. We need to go out and live among them, manifesting the gentle and loving spirit of our Lord.');
-- new verified quote: https://archive.org/download/lottiemoon0000unar/lottiemoon0000unar_djvu.txt — c. p. 145 (same 1887 letter, continuing)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 87, 'Cited in Una Roberts Lawrence, Lottie Moon (1927)', 'The prayer in former times was that God would open China. God has answered that prayer, and now who goes forth to possess the land?', 'prayer,mission,calling,obedience', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 87 AND text = 'The prayer in former times was that God would open China. God has answered that prayer, and now who goes forth to possess the land?');
-- new verified quote: https://archive.org/download/lottiemoon0000unar/lottiemoon0000unar_djvu.txt — c. p. 153 (her article in the Foreign Mission Journal, December 1887, as quoted by Lawrence)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 87, 'Cited in Una Roberts Lawrence, Lottie Moon (1927)', 'The world is the field, and woman’s work for Christ is wherever there is a home to be reformed, or a soul to be redeemed.', 'calling,service,mission,women', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 87 AND text = 'The world is the field, and woman’s work for Christ is wherever there is a home to be reformed, or a soul to be redeemed.');
-- new verified quote: https://archive.org/download/lottiemoon0000unar/lottiemoon0000unar_djvu.txt — c. p. 161 (letter to the Foreign Mission Board about new Pingtu missionaries, c. 1889)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 87, 'Cited in Una Roberts Lawrence, Lottie Moon (1927)', 'If the joy of the Lord be their strength, the blessedness of the work will more than compensate for its hardships. Let them come rejoicing to sacrifice for that Lord and Master who so freely gave himself for them.', 'joy,sacrifice,mission,strength', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 87 AND text = 'If the joy of the Lord be their strength, the blessedness of the work will more than compensate for its hardships. Let them come rejoicing to sacrifice for that Lord and Master who so freely gave himself for them.');
-- new verified quote: https://archive.org/download/lottiemoon0000unar/lottiemoon0000unar_djvu.txt — c. p. 210 (letter to Dr. Willingham, Foreign Mission Board secretary, c. 1899)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 87, 'Cited in Una Roberts Lawrence, Lottie Moon (1927)', 'I wish our people could realize that our Lord’s last command is as binding as is the command to baptize.', 'obedience,mission,calling,conviction', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 87 AND text = 'I wish our people could realize that our Lord’s last command is as binding as is the command to baptize.');
-- new verified quote: https://archive.org/download/memoiroflifela02wayl/memoiroflifela02wayl_djvu.txt — Vol. II, c. p. 198–199, letter to the Corresponding Secretary, Maulmain, April 1845 (on leaving his younger children to accompany his dying wife Sarah)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 88, 'Cited in Francis Wayland, A Memoir of the Life and Labors of the Rev. Adoniram Judson (1853)', 'But I hope I can say with truth that I love Christ above all; and I am striving, in the strength of my weak faith, to gird up my mind to face and welcome all his appointments.', 'surrender,love,faith,trust', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 88 AND text = 'But I hope I can say with truth that I love Christ above all; and I am striving, in the strength of my weak faith, to gird up my mind to face and welcome all his appointments.');
-- new verified quote: https://exhibits.archives.wheaton.edu/to-carry-the-light-further/objects/media/natesaint/1360207_transcript.pdf — page 2 of letter stamped Jan. 15, 1945 (Wheaton Archives, Collection 136, Box 2, Folder 7; item page https://exhibits.archives.wheaton.edu/to-carry-the-light-further/items/obj_0052.html)
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 98, 'Letter to the Christian Airmen''s Missionary Fellowship (1945)', 'Til tonight I couldn’t see just why the Lord would want me because I have not had fitting training for the work so far but the Lord has given me an irresistible desire to take the Gospel to those who have never heard of His love.', 'calling,mission,surrender,love', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 98 AND text = 'Til tonight I couldn’t see just why the Lord would want me because I have not had fitting training for the work so far but the Lord has given me an irresistible desire to take the Gospel to those who have never heard of His love.');
-- new verified quote: https://exhibits.archives.wheaton.edu/to-carry-the-light-further/objects/media/natesaint/1360207_transcript.pdf — page 1 of letter stamped Jan. 15, 1945
INSERT INTO quotes (figure_id, source, text, themes, verified) SELECT 98, 'Letter to the Christian Airmen''s Missionary Fellowship (1945)', 'Last New Year’s eve in a watch-nite service I said “yes” to God on the missionary challenge.', 'calling,obedience,surrender,mission', true WHERE NOT EXISTS (SELECT 1 FROM quotes WHERE figure_id = 98 AND text = 'Last New Year’s eve in a watch-nite service I said “yes” to God on the missionary challenge.');
COMMIT;
