default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do |options|
    supabase_host = (options[:supabase_url] || ENV['SUPABASE_URL'] || "").gsub(/https?:\/\//, "")
    supabase_anon_key = options[:supabase_anon_key] || ENV['SUPABASE_ANON_KEY'] || ""

    setup_ci if ENV['CI']

    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_filepath: ENV['APP_STORE_CONNECT_KEY_FILEPATH']
    )

    match(
      type: "appstore",
      api_key: api_key,
      readonly: true
    )

    increment_build_number(
      build_number: ENV['BUILD_NUMBER'] || Time.now.to_i.to_s,
      xcodeproj: "iosApp/iosApp.xcodeproj"
    )

    build_app(
      scheme: "iosApp",
      workspace: "iosApp/iosApp.xcworkspace",
      export_method: "app-store",
      configuration: "Release",
      xcargs: "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=#{ENV['APPLE_TEAM_ID']} PROVISIONING_PROFILE_SPECIFIER='match AppStore com.thecouragepost.app' CODE_SIGN_IDENTITY='Apple Distribution' SUPABASE_HOST='#{supabase_host}' SUPABASE_ANON_KEY='#{supabase_anon_key}' CURRENT_PROJECT_VERSION='#{ENV['BUILD_NUMBER'] || Time.now.to_i.to_s}'"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
